version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017 # Expose MongoDB port to the host
    volumes:
      - mongo-data:/data/db # Named volume for persisting MongoDB data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root # Set MongoDB root username
      - MONGO_INITDB_ROOT_PASSWORD=password # Set MongoDB root password
      - MONGO_INITDB_DATABASE=ecomm
    networks:
      - network1 # Use a custom network for service communication

  server:
    container_name: ecomm-server
    ports:
      - 3000:3000
    build:
      context: ./server
      dockerfile: Dockerfile

    command: npm run dev
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - network1
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017

volumes:
  mongo-data: # Define a named volume for MongoDB data persistence

networks:
  network1: # Define a custom network for service communication
